CREATE DATABASE IF NOT EXISTS atendeez_db;
USE atendeez_db;

-- 1. Admins Table
CREATE TABLE IF NOT EXISTS Admins (
    admin_id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL
);

-- 2. Teachers Table
CREATE TABLE IF NOT EXISTS Teachers (
    uTID VARCHAR(20) PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    middle_name VARCHAR(50),
    last_name VARCHAR(50) NOT NULL,
    department VARCHAR(100),
    email VARCHAR(100) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    status ENUM('Active', 'Archived') DEFAULT 'Active',
    failed_attempts INT DEFAULT 0,
    lockout_time DATETIME NULL
);

-- 3. Students Table
CREATE TABLE IF NOT EXISTS Students (
    uSID VARCHAR(20) PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    middle_name VARCHAR(50),
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    course VARCHAR(100),
    level VARCHAR(20),
    section VARCHAR(50),
    status ENUM('Active', 'Archived') DEFAULT 'Active',
    failed_attempts INT DEFAULT 0,
    lockout_time DATETIME NULL
);

-- 4. Subjects Table
CREATE TABLE IF NOT EXISTS Subjects (
    subject_id INT AUTO_INCREMENT PRIMARY KEY,
    subject_code VARCHAR(20) UNIQUE NOT NULL,
    subject_name VARCHAR(100) NOT NULL
);

-- 5. Teacher Assignments Table
CREATE TABLE IF NOT EXISTS Teacher_Assignments (
    assignment_id INT AUTO_INCREMENT PRIMARY KEY,
    uTID VARCHAR(20),
    subject_id INT,
    section VARCHAR(50),
    FOREIGN KEY (uTID) REFERENCES Teachers(uTID) ON DELETE CASCADE,
    FOREIGN KEY (subject_id) REFERENCES Subjects(subject_id) ON DELETE CASCADE
);

-- 6. Enrollments Table (Students enrolled in subjects/sections)
CREATE TABLE IF NOT EXISTS Enrollments (
    enrollment_id INT AUTO_INCREMENT PRIMARY KEY,
    uSID VARCHAR(20),
    subject_id INT,
    section VARCHAR(50),
    FOREIGN KEY (uSID) REFERENCES Students(uSID) ON DELETE CASCADE,
    FOREIGN KEY (subject_id) REFERENCES Subjects(subject_id) ON DELETE CASCADE
);

-- 7. Schedule Table (Class timings)
CREATE TABLE IF NOT EXISTS schedule (
    schedule_id INT AUTO_INCREMENT PRIMARY KEY,
    subject_id INT,
    uTID VARCHAR(20),
    section VARCHAR(50),
    day_of_week VARCHAR(20),
    start_time TIME,
    end_time TIME,
    room VARCHAR(50),
    FOREIGN KEY (subject_id) REFERENCES Subjects(subject_id) ON DELETE CASCADE,
    FOREIGN KEY (uTID) REFERENCES Teachers(uTID) ON DELETE CASCADE
);

-- 7. Sessions Table (QR generated by teachers)
CREATE TABLE IF NOT EXISTS Sessions (
    session_id VARCHAR(50) PRIMARY KEY,
    uTID VARCHAR(20),
    subject_id INT,
    section VARCHAR(50),
    random_token VARCHAR(50) NOT NULL,
    start_time DATETIME NOT NULL,
    expires_at DATETIME NOT NULL,
    latitude DECIMAL(10, 8),
    longitude DECIMAL(11, 8),
    status ENUM('Active', 'Ended') DEFAULT 'Active',
    FOREIGN KEY (uTID) REFERENCES Teachers(uTID),
    FOREIGN KEY (subject_id) REFERENCES Subjects(subject_id)
);

-- 8. Attendance Table
CREATE TABLE IF NOT EXISTS Attendance (
    attendance_id INT AUTO_INCREMENT PRIMARY KEY,
    session_id VARCHAR(50),
    uSID VARCHAR(20),
    scan_time DATETIME NOT NULL,
    status ENUM('Present', 'Absent', 'Late') DEFAULT 'Present',
    remarks VARCHAR(255),
    is_valid ENUM('Valid', 'Invalid') DEFAULT 'Valid', -- For tab switching/suspicious activity
    FOREIGN KEY (session_id) REFERENCES Sessions(session_id),
    FOREIGN KEY (uSID) REFERENCES Students(uSID),
    UNIQUE KEY unique_scan (session_id, uSID) -- Prevent duplicate scans in same session
);

-- 9. Notifications Table
CREATE TABLE IF NOT EXISTS Notifications (
    notification_id INT AUTO_INCREMENT PRIMARY KEY,
    uSID VARCHAR(20),
    message VARCHAR(255) NOT NULL,
    type ENUM('Info', 'Warning', 'Alert') DEFAULT 'Info',
    is_read BOOLEAN DEFAULT FALSE,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (uSID) REFERENCES Students(uSID) ON DELETE CASCADE
);

-- 10. Submitted Reports Table
CREATE TABLE IF NOT EXISTS Submitted_Reports (
    report_id INT AUTO_INCREMENT PRIMARY KEY,
    uTID VARCHAR(20),
    subject_id INT,
    section VARCHAR(50),
    submission_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    summary_json LONGTEXT,
    status ENUM('Submitted', 'Reviewed') DEFAULT 'Submitted',
    FOREIGN KEY (uTID) REFERENCES Teachers(uTID),
    FOREIGN KEY (subject_id) REFERENCES Subjects(subject_id)
);

-- 11. Drop Requests Table (Teacher requests to archive student)
CREATE TABLE IF NOT EXISTS Drop_Requests (
    request_id INT AUTO_INCREMENT PRIMARY KEY,
    uTID VARCHAR(20),
    uSID VARCHAR(20),
    subject_id INT,
    reason TEXT,
    status ENUM('Pending', 'Approved', 'Rejected') DEFAULT 'Pending',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (uTID) REFERENCES Teachers(uTID),
    FOREIGN KEY (uSID) REFERENCES Students(uSID),
    FOREIGN KEY (subject_id) REFERENCES Subjects(subject_id)
);

-- 12. Excuse Letters Table
CREATE TABLE IF NOT EXISTS Excuse_Letters (
    letter_id INT AUTO_INCREMENT PRIMARY KEY,
    uSID VARCHAR(20),
    uTID VARCHAR(20),
    subject_id INT,
    message TEXT NOT NULL,
    file_path VARCHAR(255),
    status ENUM('Pending', 'Approved', 'Rejected') DEFAULT 'Pending',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (uSID) REFERENCES Students(uSID),
    FOREIGN KEY (uTID) REFERENCES Teachers(uTID),
    FOREIGN KEY (subject_id) REFERENCES Subjects(subject_id)
);

-- =========================================
-- SAMPLE DATA — Password for all accounts: password123
-- Hash generated with werkzeug.security.generate_password_hash('password123')
-- =========================================

-- Admin account
INSERT IGNORE INTO Admins (username, password_hash, email) VALUES
('admin1', 'scrypt:32768:8:1$N82dGZp1t2rZ4B5y$4f10738eb2023d0611a21e428c9b98ff3c69c670ca7a1cbb612b7a0d4c82db7b4613fffc81e5932df8c42a2e6f47702f37c7689975765db805b53b817c763b65', 'admin@atendeez.com'); -- Password: password123

-- =========================================
-- SUBJECTS — 3 courses offered
-- =========================================
INSERT IGNORE INTO Subjects (subject_code, subject_name) VALUES
('IT101', 'Introduction to Computing'),   -- subject_id = 1
('IT102', 'Programming 1'),               -- subject_id = 2
('IT103', 'Database Management Systems'); -- subject_id = 3

-- =========================================
-- TEACHERS — T-YYYY-XXX format, 2 teachers
-- =========================================
INSERT IGNORE INTO Teachers (uTID, first_name, middle_name, last_name, department, email, password_hash) VALUES
-- Teacher 1: handles IT101 and IT102 for Section A
('T-2024-001', 'John',  'D.', 'Doe',    'IT Department', 'johndoe@example.com',   'scrypt:32768:8:1$N82dGZp1t2rZ4B5y$4f10738eb2023d0611a21e428c9b98ff3c69c670ca7a1cbb612b7a0d4c82db7b4613fffc81e5932df8c42a2e6f47702f37c7689975765db805b53b817c763b65'),
-- Teacher 2: handles IT103 for Section B
('T-2024-002', 'Maria', 'S.', 'Santos', 'CS Department', 'mariasantos@example.com','scrypt:32768:8:1$N82dGZp1t2rZ4B5y$4f10738eb2023d0611a21e428c9b98ff3c69c670ca7a1cbb612b7a0d4c82db7b4613fffc81e5932df8c42a2e6f47702f37c7689975765db805b53b817c763b65');

-- =========================================
-- STUDENTS — S-YYYY-XXX format, 5 students
-- =========================================
INSERT IGNORE INTO Students (uSID, first_name, middle_name, last_name, email, password_hash, course, level, section) VALUES
-- Section A students (taught by John Doe)
('S-2024-001', 'Juan',   'A.', 'Dela Cruz', 'juan@student.com',  'scrypt:32768:8:1$N82dGZp1t2rZ4B5y$4f10738eb2023d0611a21e428c9b98ff3c69c670ca7a1cbb612b7a0d4c82db7b4613fffc81e5932df8c42a2e6f47702f37c7689975765db805b53b817c763b65', 'BSIT', '1st Year', 'A'),
('S-2024-002', 'Ana',    'B.', 'Reyes',     'ana@student.com',   'scrypt:32768:8:1$N82dGZp1t2rZ4B5y$4f10738eb2023d0611a21e428c9b98ff3c69c670ca7a1cbb612b7a0d4c82db7b4613fffc81e5932df8c42a2e6f47702f37c7689975765db805b53b817c763b65', 'BSIT', '1st Year', 'A'),
('S-2024-003', 'Carlos', 'C.', 'Garcia',    'carlos@student.com','scrypt:32768:8:1$N82dGZp1t2rZ4B5y$4f10738eb2023d0611a21e428c9b98ff3c69c670ca7a1cbb612b7a0d4c82db7b4613fffc81e5932df8c42a2e6f47702f37c7689975765db805b53b817c763b65', 'BSIT', '1st Year', 'A'),
-- Section B students (taught by Maria Santos)
('S-2024-004', 'Mark',   'D.', 'Lopez',     'mark@student.com',  'scrypt:32768:8:1$N82dGZp1t2rZ4B5y$4f10738eb2023d0611a21e428c9b98ff3c69c670ca7a1cbb612b7a0d4c82db7b4613fffc81e5932df8c42a2e6f47702f37c7689975765db805b53b817c763b65', 'BSCS', '2nd Year', 'B'),
('S-2024-005', 'Sofia',  'E.', 'Mendoza',   'sofia@student.com', 'scrypt:32768:8:1$N82dGZp1t2rZ4B5y$4f10738eb2023d0611a21e428c9b98ff3c69c670ca7a1cbb612b7a0d4c82db7b4613fffc81e5932df8c42a2e6f47702f37c7689975765db805b53b817c763b65', 'BSCS', '2nd Year', 'B');

-- =========================================
-- TEACHER ASSIGNMENTS — which teacher handles which subject + section
-- A teacher CAN handle multiple subjects/sections
-- =========================================
INSERT IGNORE INTO Teacher_Assignments (uTID, subject_id, section) VALUES
('T-2024-001', 1, 'A'),  -- John Doe   → IT101, Section A
('T-2024-001', 2, 'A'),  -- John Doe   → IT102, Section A
('T-2024-002', 3, 'B');  -- Maria Santos → IT103, Section B

-- =========================================
-- ENROLLMENTS — which students are in which subject + section
-- This is the KEY table that connects students TO their teacher's class
-- =========================================
INSERT IGNORE INTO Enrollments (uSID, subject_id, section) VALUES
-- Juan, Ana, Carlos → enrolled under John Doe in IT101 Section A
('S-2024-001', 1, 'A'),
('S-2024-002', 1, 'A'),
('S-2024-003', 1, 'A'),
-- Juan and Ana also take IT102 Section A (still John Doe)
('S-2024-001', 2, 'A'),
('S-2024-002', 2, 'A'),
-- Mark and Sofia → enrolled under Maria Santos in IT103 Section B
('S-2024-004', 3, 'B'),
('S-2024-005', 3, 'B');

-- Stored Procedure: Record Attendance with GPS check and Validity
DELIMITER //
CREATE PROCEDURE sp_RecordAttendance(
    IN p_student_id VARCHAR(20),
    IN p_session_id VARCHAR(50),
    IN p_token VARCHAR(50),
    IN p_student_lat DECIMAL(10,8),
    IN p_student_lon DECIMAL(11,8),
    IN p_is_valid ENUM('Valid', 'Invalid'),
    OUT p_result VARCHAR(255)
)
BEGIN
    DECLARE v_teacher_lat DECIMAL(10,8);
    DECLARE v_teacher_lon DECIMAL(11,8);
    DECLARE v_expires_at DATETIME;
    DECLARE v_session_token VARCHAR(50);
    DECLARE v_status ENUM('Active', 'Ended');
    DECLARE v_distance DECIMAL(10,2);
    DECLARE v_exists INT;
    
    -- Check if student is already marked for this session
    SELECT COUNT(*) INTO v_exists FROM Attendance WHERE session_id = p_session_id AND uSID = p_student_id;
    
    IF v_exists > 0 THEN
        SET p_result = 'Already scanned for this session.';
    ELSE
        -- Get Session details
        SELECT latitude, longitude, expires_at, random_token, status 
        INTO v_teacher_lat, v_teacher_lon, v_expires_at, v_session_token, v_status
        FROM Sessions WHERE session_id = p_session_id;
        
        IF v_status = 'Ended' THEN
            SET p_result = 'Session has already ended.';
        ELSEIF NOW() > v_expires_at THEN
            SET p_result = 'QR Code has expired.';
        ELSEIF p_token != v_session_token THEN
            SET p_result = 'Invalid QR Token.';
        ELSE
            -- Calculate distance in meters using Haversine formula (Earth radius ~ 6371km)
            SET v_distance = 6371000 * ACOS(
                COS(RADIANS(v_teacher_lat)) * COS(RADIANS(p_student_lat)) *
                COS(RADIANS(p_student_lon) - RADIANS(v_teacher_lon)) +
                SIN(RADIANS(v_teacher_lat)) * SIN(RADIANS(p_student_lat))
            );
            
            IF v_distance > 50 THEN
                SET p_result = CONCAT('Out of range. Distance: ', ROUND(v_distance, 0), ' meters. Allowed: 50m.');
            ELSE
                -- Insert Attendance
                INSERT INTO Attendance (session_id, uSID, scan_time, status, is_valid)
                VALUES (p_session_id, p_student_id, NOW(), 'Present', p_is_valid);
                
                -- Insert Notification
                INSERT INTO Notifications (uSID, message, type)
                VALUES (p_student_id, CONCAT('Attendance marked Present for session: ', p_session_id), 'Info');
                
                IF p_is_valid = 'Invalid' THEN
                    SET p_result = 'Success but flagged for suspicious activity.';
                ELSE
                    SET p_result = 'Attendance successfully recorded.';
                END IF;
            END IF;
        END IF;
    END IF;
END //
DELIMITER ;
